package server

import (
	"fmt"
	"sort"
	"strings"
	"time"
)

// This file holds story 09 of the wikiskill evolution support plan: the
// Trained Skill Result report (Phase C5) and the data the wizard's Review and
// Report steps read (Phase D3).
//
// THE REPORT: when an evolution run ends — accepted, exhausted, plateaued,
// cancelled, or failed — the wiki itself (Go, from stored records; never a
// model call) writes ONE wiki article per run. The article is generated once
// and never rewritten: the job record carries result_report_slug, and every
// finalize path calls EnsureSkillResultReport, which returns the existing
// article instead of creating a second one. A failed run gets a "no
// promotion" report carrying the lessons (the reason the run ended, the
// patterns its iterations touched) — a terminated run never dead-ends without
// a record. The report always reflects the run END: EnsureSkillResultReport
// refuses a job that is not terminal (the terminal gate), so a claim or a
// heartbeat can never mint a report whose outcome label had not happened yet.
//
// IMMUTABILITY CONVENTION: agents cannot edit a report after creation. The
// report carries the tool-managed `wikiskill-report` marker tag, mirroring the
// story-06 trained-marker mechanics: validateAndCleanUserTags (handlers.go)
// preserves the tag on any edit and strips it when forged onto a document that
// does not have it; saveArticleLocked (storage.go) re-asserts a tag a write
// path dropped; DeleteTagGlobally refuses it outright. The agent-facing edit
// REFUSALS live at the MCP tool layer (edit_wiki_article, update_article_tags,
// revert_article_version, delete_wiki_article in mcp_tools_articles.go) — the
// same boundary the skill lock refused at in story 01 — so the human-facing
// REST editor keeps the documented amend path (the template's Amendments
// footer explains appending a visible note) while every agent write tool
// refuses.
//
// STALENESS IS DERIVED, NEVER STORED: the report body records the trained
// state as it stood at publication, but the article is immutable, so live
// staleness (eval set re-uploaded after the run, marker revoked) is served by
// SkillResultReportView reusing deriveSkillTrainedState — the same value the
// wizard's Review and Report steps render.
//
// FINALIZATION HOOKS: EnsureSkillResultReport runs best-effort outside
// writeMu from the terminal transitions (completeLoopJob in skill_loop.go;
// CompleteEvolutionJob, CancelEvolutionJob, and RequeueExpiredJobs in
// skill_jobs.go; the run-cap-refused claim in ClaimEvolutionJob), so every way
// a run can end lands a report. A report write failure is logged to Stderr and
// never fails the stop itself. The terminal gate inside refuses a job that has
// not ended, so no finalize path — and no stray caller — can generate a report
// mid-run.
//
// SKILL↔REPORT LINKS: the report body always links back to its skill (the Run
// table). The reverse link — the "Trained Skill Result reports" section
// appended to the skill article — is written ONLY when the run promoted a
// candidate (a gate accept): the story-07 invariants make a rejection or an
// abort leave the live skill byte-identical, and the report carries the run's
// record either way, so a no-promotion run touches the skill not at all.
//
// NOT BUILT HERE (later stories own these): eval-store/scorer versioning
// (story 11) and budget enforcement (F3) — the report records those fields as
// they are stored, with the honest limitation notes.

// SkillResultReportTag is the tool-managed marker tag stamped on the report
// article the wiki generated for one completed run. Agents cannot forge it
// onto other documents and cannot strip it from a report.
const SkillResultReportTag = "wikiskill-report"

// ReportImmutableError reports a refused agent write to a Trained Skill
// Result report. The message names the article and the convention, so an
// agent reading the refusal knows the report is the record, not a draft.
type ReportImmutableError struct {
	Slug string
}

func (e *ReportImmutableError) Error() string {
	return fmt.Sprintf("article '%s' is a Trained Skill Result report: it was generated by the wiki's own Go code from stored run records and agents cannot edit it — humans may amend it through the editor by appending a dated note (the report's Amendments footer explains the convention)", e.Slug)
}

// checkReportImmutability returns a *ReportImmutableError when art is a
// generated result report, nil otherwise. Called by the agent-facing MCP write
// tools; the human-facing REST editor deliberately does not call it, so a
// human amend stays possible while every agent path is refused.
func checkReportImmutability(art *Article) error {
	if art != nil && hasTag(art.Tags, SkillResultReportTag) {
		return &ReportImmutableError{Slug: art.Slug}
	}
	return nil
}

// SkillResultReportRef points at the report article one run generated.
type SkillResultReportRef struct {
	Slug      string    `json:"slug"`
	Title     string    `json:"title"`
	URL       string    `json:"url"`
	CreatedAt time.Time `json:"created_at,omitzero"`
}

// SkillResultReportView is the wizard's Report-step body: the run's terminal
// shape, the report link (absent until the run ends), and the skill's LIVE
// derived trained state — staleness is derived at serve time and reused from
// skill_trained.go, because the immutable report cannot update itself.
// TrainedState is nil when the skill document is gone; the report survives.
type SkillResultReportView struct {
	JobID        string                `json:"job_id"`
	SkillSlug    string                `json:"skill_slug"`
	Status       string                `json:"status"`
	LoopOutcome  string                `json:"loop_outcome,omitempty"`
	Terminal     bool                  `json:"terminal"`
	Report       *SkillResultReportRef `json:"report,omitempty"`
	TrainedState *SkillTrainedState    `json:"trained_state,omitempty"`
}

// SkillResultReportViewFor derives the served view for one job.
func (s *Storage) SkillResultReportViewFor(job *EvolutionJob) (*SkillResultReportView, error) {
	view := &SkillResultReportView{
		JobID:       job.ID,
		SkillSlug:   job.SkillSlug,
		Status:      job.Status,
		LoopOutcome: job.LoopOutcome,
		Terminal:    evolutionJobTerminal(job.Status),
	}
	if art, err := s.GetArticle(job.ResultReportSlug); err == nil && job.ResultReportSlug != "" {
		view.Report = &SkillResultReportRef{
			Slug:      art.Slug,
			Title:     art.Title,
			URL:       "/articles/" + art.Slug,
			CreatedAt: art.CreatedAt,
		}
	}
	if state, err := s.GetSkillTrainedState(job.SkillSlug); err == nil {
		view.TrainedState = &state.SkillTrainedState
	}
	return view, nil
}

// reportSlugStamp records the report article on the job record. Callers hold
// Storage.writeMu.
func (s *Storage) stampReportSlug(job *EvolutionJob, slug string) error {
	if job.ResultReportSlug == slug {
		return nil
	}
	job.ResultReportSlug = slug
	return s.writeEvolutionJob(job)
}

// EnsureSkillResultReport creates the run's Trained Skill Result report
// exactly once and — when the run promoted a candidate — links it from the
// skill article. TERMINAL GATE: only an ended run (complete, failed, timeout,
// cancelled) generates a report; a queued/claimed/running/paused job is
// refused, because the report must reflect the run END, never a mid-run
// state. Idempotent: a job whose result_report_slug resolves returns the
// existing article; a stamp whose article was deleted re-creates the report
// from the stored records, so a report can never be lost behind a stale
// pointer. Safe to call from every finalize path, repeatedly.
func (s *Storage) EnsureSkillResultReport(jobID string) (*Article, error) {
	s.writeMu.Lock()
	defer s.writeMu.Unlock()

	job, err := s.GetEvolutionJob(jobID)
	if err != nil {
		return nil, err
	}

	// Terminal gate: a run that has not ended has no outcome to report. Only
	// terminal jobs (complete/failed/timeout/cancelled) generate — and only
	// they carry a real terminal outcome, so the report's outcome label can
	// never read a mid-run status like "claimed".
	if !evolutionJobTerminal(job.Status) {
		return nil, fmt.Errorf("evolution job '%s' has not ended (status %s) — the result report is generated only when the run ends", job.ID, job.Status)
	}

	// Idempotent lookups, in order: the job's own stamp, then any existing
	// report article carrying this run's ID (covers a crash between the report
	// write and the job stamp).
	if job.ResultReportSlug != "" {
		if art, gerr := s.GetArticle(job.ResultReportSlug); gerr == nil {
			return art, s.ensureSkillReportLink(job, art)
		}
	}
	if found, ferr := s.findResultReportForJob(job); ferr == nil && found != nil {
		if serr := s.stampReportSlug(job, found.Slug); serr != nil {
			logRunnerf("result report for job %s found but the stamp failed: %v", job.ID, serr)
		}
		return found, s.ensureSkillReportLink(job, found)
	}

	skill, err := s.GetArticle(job.SkillSlug)
	if err != nil {
		return nil, fmt.Errorf("cannot generate result report for job '%s': skill not found: %s", job.ID, job.SkillSlug)
	}
	if skill.Type != ContentTypeSkill {
		return nil, fmt.Errorf("cannot generate result report for job '%s': '%s' is no longer a Custom AI Skill", job.ID, job.SkillSlug)
	}
	iterations, err := s.ListIterationRecords(job.ID)
	if err != nil {
		return nil, err
	}
	auditAll, err := s.ListSkillAuditRecords()
	if err != nil {
		return nil, err
	}
	audit := make([]SkillAuditRecord, 0, len(auditAll))
	for _, rec := range auditAll {
		if rec.SkillSlug == job.SkillSlug {
			audit = append(audit, rec)
		}
	}
	var eval *EvalMeta
	if _, _, meta, rerr := s.ReadEvolutionEvalSet(job.ID); rerr == nil {
		eval = &meta
	}
	currentEvalHash, err := s.latestEvalHashForSkill(job.SkillSlug)
	if err != nil {
		return nil, err
	}
	trained := deriveSkillTrainedState(skill, currentEvalHash)

	title := fmt.Sprintf("Trained Skill Result: %s (run %s)", skill.Title, job.ID)
	description := fmt.Sprintf("Auto-generated WikiSkill evolution report — run %s, outcome %s.", job.ID, resultOutcomeLabel(job))
	content := composeResultReport(job, skill, iterations, audit, eval, trained)

	art, err := s.saveArticleLocked("", title, content, description, "", "",
		reportEditSummary(job), []string{SkillResultReportTag}, ContentTypeWiki, ArticleOverrides{})
	if err != nil {
		return nil, err
	}
	if serr := s.stampReportSlug(job, art.Slug); serr != nil {
		logRunnerf("result report for job %s generated but the stamp failed: %v", job.ID, serr)
	}
	if lerr := s.ensureSkillReportLink(job, art); lerr != nil {
		logRunnerf("skill→report link for job %s failed: %v", job.ID, lerr)
	}
	logRunnerf("result report generated for job %s: /articles/%s", job.ID, art.Slug)
	return art, nil
}

// ensureResultReportBestEffort is the finalize-path wrapper: report
// generation must never fail a stop that already succeeded.
func (s *Storage) ensureResultReportBestEffort(jobID string) {
	if _, err := s.EnsureSkillResultReport(jobID); err != nil {
		logRunnerf("result report for job %s could not be generated: %v", jobID, err)
	}
}

// reportEditSummary is the report creation's edit summary.
func reportEditSummary(job *EvolutionJob) string {
	return fmt.Sprintf("Generated Trained Skill Result report for run %s (outcome %s)", job.ID, resultOutcomeLabel(job))
}

// findResultReportForJob scans the corpus for a report article already
// carrying this run's ID — the recovery path when a generation was interrupted
// between the article write and the job stamp. Report articles are rare, so
// the linear scan is cheap.
func (s *Storage) findResultReportForJob(job *EvolutionJob) (*Article, error) {
	metas, err := s.ListArticles()
	if err != nil {
		return nil, err
	}
	for i := range metas {
		meta := &metas[i]
		if meta.Type != ContentTypeWiki || !hasTag(meta.Tags, SkillResultReportTag) {
			continue
		}
		art, err := s.GetArticle(meta.Slug)
		if err != nil {
			continue
		}
		if strings.Contains(art.Content, job.ID) {
			return art, nil
		}
	}
	return nil, nil
}

// ensureSkillReportLink appends the skill→report link block — but ONLY when
// the run promoted a candidate (a gate accept). The story-07 invariants make
// a rejection and an abort leave the live skill byte-identical: a
// no-promotion run's report still exists and already links the skill, but the
// skill itself is not touched, so the skill gets its backlink section only on
// accept. The append re-stamps the active trained marker on the version this
// save writes, so the marker keeps naming the live version (otherwise the
// append itself would read as post-training drift and flag the marker stale).
// The original training metadata (time, parent, candidate, score, eval hash)
// is preserved; a revoked marker stays revoked — the revocation is history.
// Callers hold Storage.writeMu.
func (s *Storage) ensureSkillReportLink(job *EvolutionJob, report *Article) error {
	skill, err := s.GetArticle(job.SkillSlug)
	if err != nil {
		// The skill was deleted after the run: the report survives and stands
		// alone; the link cannot be written. Not a generation failure.
		logRunnerf("result report for job %s has no skill to link ('%s'): %v", job.ID, job.SkillSlug, err)
		return nil
	}
	if skill.Type != ContentTypeSkill || strings.Contains(skill.Content, "/articles/"+report.Slug) {
		return nil
	}
	// Promotion gate: the backlink section is an append to the live skill, and
	// the story-07 contract is that a run which promoted nothing never edits
	// it. Only a run whose own gate accepted at least one candidate may write.
	iterations, err := s.ListIterationRecords(job.ID)
	if err != nil {
		return err
	}
	if !runPromoted(iterations) {
		return nil
	}
	if active, aerr := s.activeEvolutionJobForSkill(skill.Slug); aerr == nil && active != nil {
		logRunnerf("skipping skill→report link for '%s': evolution job '%s' is %s", skill.Slug, active.ID, active.Status)
		return nil
	}

	section := fmt.Sprintf("\n\n## Trained Skill Result reports\n\n[%s](/articles/%s) — auto-generated report for run `%s`.\n",
		report.Title, report.Slug, job.ID)

	var stamp *TrainedStamp
	if hasTag(skill.Tags, TrainedMarkerTag) && skill.TrainedRevokedAt.IsZero() && (skill.TrainedVersion > 0 || !skill.TrainedAt.IsZero()) {
		stamp = &TrainedStamp{
			At:            skill.TrainedAt,
			ParentVersion: skill.TrainedParentVersion,
			CandidateID:   skill.TrainedCandidate,
			ValScore:      skill.TrainedValScore,
			EvalHash:      skill.TrainedEvalHash,
		}
	}
	_, err = s.saveArticleLocked(skill.Slug, skill.Title, skill.Content+section, skill.Description,
		skill.Source, skill.Resource, fmt.Sprintf("Linked Trained Skill Result report for run %s", job.ID),
		skill.Tags, skill.Type, ArticleOverrides{TrainedStamp: stamp})
	return err
}

// runPromoted reports whether this run's own gate accepted at least one
// candidate — the story-07 accept path that promotes onto the live skill
// (every rejection auto-reverts, so a run's accepted body is the last one the
// run left). It reads the run's ITERATION records, not the skill's audit
// trail: a marker or an accept decision that predates or sidesteps this run's
// loop (a pre-seeded promote) is not this run's promotion. Used to gate the
// skill→report backlink append.
func runPromoted(iterations []IterationRecord) bool {
	for _, rec := range iterations {
		if rec.Outcome == IterationOutcomeAccepted {
			return true
		}
	}
	return false
}

// resultOutcomeLabel renders the run's end for the report header: the loop
// outcome when the loop recorded one, otherwise the terminal job status
// mapped into the designed-stop vocabulary. The terminal gate guarantees only
// ended runs reach this, so the label is always a real terminal outcome and
// never a mid-run status like "claimed".
func resultOutcomeLabel(job *EvolutionJob) string {
	if s := strings.TrimSpace(job.LoopOutcome); s != "" {
		return s
	}
	return loopOutcomeForJobStatus(job.Status)
}

// resultOutcomeReason renders why the run ended: the cancel reason, then the
// error, then the last progress note (where completeLoopJob parks the stop
// reason).
func resultOutcomeReason(job *EvolutionJob) string {
	for _, v := range []string{job.CancelReason, job.Error, job.ProgressNote} {
		if s := strings.TrimSpace(v); s != "" {
			return s
		}
	}
	return ""
}

// resultOutcomeVerb is the one-line "what happened" — the no-promotion
// variant's honest summary for every stop that did not promote.
func resultOutcomeVerb(job *EvolutionJob) string {
	switch {
	case job.LoopOutcome == LoopOutcomeCompleted:
		return "The loop stopped on a designed stop condition with its best candidate promoted."
	case job.LoopOutcome != "" || job.Status == EvolutionJobFailed ||
		job.Status == EvolutionJobCancelled || job.Status == EvolutionJobTimeout:
		return "No promotion — the skill stays at its last accepted version."
	default:
		return "The run ended without promoting a candidate."
	}
}

// runFinalRBest resolves the run's final R_best for the report: the highest
// R_best_after among the skill's audit records from this run onward (the
// audit trail is the source of record), falling back through the run's own
// iteration records, the trained marker, and the skill's whole trail — so the
// report is never invented from nothing. The second return names the source
// the number came from; "" means no gate history exists at all.
func runFinalRBest(job *EvolutionJob, iterations []IterationRecord, audit []SkillAuditRecord, trained SkillTrainedState) (float64, string) {
	var best float64
	for _, rec := range audit {
		if !rec.Timestamp.Before(job.CreatedAt) && rec.RBestAfter > best {
			best = rec.RBestAfter
		}
	}
	if best > 0 {
		return best, "this run's gate decisions"
	}
	for _, rec := range iterations {
		if (rec.Outcome == IterationOutcomeAccepted || rec.Outcome == IterationOutcomeRejected) && rec.RBest > best {
			best = rec.RBest
		}
	}
	if best > 0 {
		return best, "the run's iteration records"
	}
	if trained.TrainedVersion > 0 {
		return trained.TrainedValScore, "the trained marker"
	}
	var trail float64
	for _, rec := range audit {
		if rec.RBestAfter > trail {
			trail = rec.RBestAfter
		}
	}
	if trail > 0 {
		return trail, "the skill's audit trail"
	}
	return 0, ""
}

// resultVersions returns the pre-run and post-run version cells: the marker
// metadata carries the trained version and the version it was cut from; a run
// that promoted nothing reports the live version as unchanged.
func resultVersions(trained SkillTrainedState, liveVersion int) (pre, post string) {
	if trained.TrainedVersion > 0 {
		preCell := "—"
		if trained.TrainedParentVersion > 0 {
			preCell = fmt.Sprintf("v%d", trained.TrainedParentVersion)
		}
		postCell := fmt.Sprintf("v%d (trained", trained.TrainedVersion)
		if s := strings.TrimSpace(trained.TrainedCandidate); s != "" {
			postCell += ", candidate `" + s + "`"
		}
		if !trained.RevokedAt.IsZero() {
			postCell += ", marker revoked after training"
		}
		return preCell, postCell + ")"
	}
	return "—", fmt.Sprintf("v%d (no promotion — skill unchanged)", liveVersion)
}

// countDecidedAgainst counts iterations that were rejected or interrupted —
// the honest measure of work the run started but the gate (or a stop) ended.
func countDecidedAgainst(iterations []IterationRecord) int {
	n := 0
	for _, rec := range iterations {
		if rec.Outcome == IterationOutcomeInterrupted || rec.Outcome == IterationOutcomeRejected {
			n++
		}
	}
	return n
}

// runnerLine renders the runner identity: "not claimed" when the run never
// got that far.
func runnerLine(job *EvolutionJob) string {
	if s := strings.TrimSpace(job.Runner); s != "" {
		return s
	}
	return "not claimed"
}

// finishedLine renders the run's end time, or an honest dash when the record
// carries none.
func finishedLine(job *EvolutionJob) string {
	if job.CompletedAt.IsZero() {
		return "—"
	}
	return job.CompletedAt.UTC().Format(time.RFC3339)
}

// trainedStateAtPublication renders the publication-time trained state for
// the report's own section.
func trainedStateAtPublication(trained SkillTrainedState) string {
	switch trained.State {
	case TrainedStateTrained:
		return fmt.Sprintf("trained (v%d, val score %.4f, eval hash %.12s)", trained.TrainedVersion, trained.TrainedValScore, trained.TrainedEvalHash)
	case TrainedStateStale:
		return "stale — " + trained.Reason
	default:
		return "untrained — no candidate was promoted by this run"
	}
}

// composeResultReport renders the report body from the stored records. Every
// section is fixed template text; every value is read back from a record —
// nothing is invented here and nothing is asked of a model.
func composeResultReport(job *EvolutionJob, skill *Article, iterations []IterationRecord, audit []SkillAuditRecord, eval *EvalMeta, trained SkillTrainedState) string {
	var b strings.Builder

	outcome := resultOutcomeLabel(job)
	reason := resultOutcomeReason(job)

	fmt.Fprintf(&b, "# Trained Skill Result: %s\n\n", skill.Title)
	fmt.Fprintf(&b, "Auto-generated from this run's stored records by the wiki itself (Go harness code, not a model call). Outcome: **%s**", outcome)
	if reason != "" {
		fmt.Fprintf(&b, " — %s", reason)
	}
	b.WriteString(".\n\n")
	fmt.Fprintf(&b, "%s The skill itself was never edited by this report; every number below is read back from the stored records.\n\n", resultOutcomeVerb(job))

	// Versions.
	pre, post := resultVersions(trained, skill.Version)
	b.WriteString("## Versions\n\n")
	fmt.Fprintf(&b, "| Stage | Version |\n|---|---|\n| Before this run | %s |\n| After this run | %s |\n\n", pre, post)

	// Run window.
	b.WriteString("## Run\n\n")
	fmt.Fprintf(&b, "| Field | Value |\n|---|---|\n| Skill | [%s](/articles/%s) |\n| Run ID | `%s` |\n| Profile | %s |\n| Runner | %s |\n| Started | %s |\n| Finished | %s |\n\n",
		skill.Title, skill.Slug, job.ID, job.Profile, runnerLine(job),
		job.CreatedAt.UTC().Format(time.RFC3339), finishedLine(job))

	// Evaluation set.
	b.WriteString("## Evaluation set\n\n")
	if eval == nil {
		b.WriteString("No eval set was uploaded for this run — the format gate never accepted training data, so no baseline exists and every gate decision compared against a zero R_best.\n\n")
	} else {
		fmt.Fprintf(&b, "| Field | Value |\n|---|---|\n| Source file | %s |\n| Split mode | %s |\n| Train / val cases | %d / %d |\n| Eval hash | `%s` |\n| Scorer version | %s |\n| Uploaded | %s |\n\n",
			eval.Filename, eval.SplitMode, eval.TrainCount, eval.ValCount, eval.EvalHash, eval.ScorerVersion,
			eval.UploadedAt.UTC().Format(time.RFC3339))
	}

	// Scores: baseline vs final.
	b.WriteString("## Scores: baseline vs final\n\n")
	s0Cell := "not scored (no eval set)"
	finalCell := "not scored"
	rBest, rBestSource := runFinalRBest(job, iterations, audit, trained)
	if rBestSource != "" {
		finalCell = fmt.Sprintf("%.2f%% (R_best via %s)", rBest*100, rBestSource)
	}
	if eval != nil {
		s0Cell = fmt.Sprintf("%.2f%% (S0, %s baseline scorer)", eval.BaselineS0*100, eval.ScorerVersion)
	}
	b.WriteString("| Split | Baseline (S0) | Final |\n|---|---|---|\n")
	fmt.Fprintf(&b, "| val | %s | %s |\n", s0Cell, finalCell)
	b.WriteString("| train | — (the v0 scorer scores the val split only) | — |\n\n")
	if eval != nil && rBestSource != "" {
		fmt.Fprintf(&b, "Δ vs baseline: %+.4f (S0 %.4f → R_best %.4f).\n\n", rBest-eval.BaselineS0, eval.BaselineS0, rBest)
	}

	// Iteration history.
	b.WriteString("## Iteration history\n\n")
	if len(iterations) == 0 {
		b.WriteString("No iterations were recorded — the run ended before the loop started.\n\n")
	} else {
		b.WriteString("| # | Candidate | Patterns | Val score | R_best | Outcome |\n|---|---|---|---|---|---|\n")
		for _, rec := range iterations {
			candCell := "none proposed"
			if rec.CandidateID != "" {
				candCell = "`" + rec.CandidateID + "`"
			}
			patternCell := "—"
			if len(rec.PatternSlugs) > 0 {
				quoted := make([]string, 0, len(rec.PatternSlugs))
				for _, p := range rec.PatternSlugs {
					quoted = append(quoted, "`"+p+"`")
				}
				patternCell = strings.Join(quoted, ", ")
			}
			outcomeCell := rec.Outcome
			if outcomeCell == "" {
				outcomeCell = "in flight"
			}
			if rec.ResultVersion > 0 {
				outcomeCell = fmt.Sprintf("%s (promoted v%d)", outcomeCell, rec.ResultVersion)
			}
			fmt.Fprintf(&b, "| %d | %s | %s | %.4f | %.4f | %s |\n",
				rec.Iteration, candCell, patternCell, rec.ValScore, rec.RBest, outcomeCell)
		}
		b.WriteString("\n")
	}

	// Patterns added, with first-touch attribution.
	b.WriteString("## Patterns added\n\n")
	firstTouched := map[string]int{}
	order := []string{}
	for _, rec := range iterations {
		for _, slug := range rec.PatternSlugs {
			if _, ok := firstTouched[slug]; !ok {
				firstTouched[slug] = rec.Iteration
				order = append(order, slug)
			}
		}
	}
	sort.Strings(order)
	if len(order) == 0 {
		b.WriteString("none — no iteration of this run touched a wiki pattern slug.\n\n")
	} else {
		for _, slug := range order {
			fmt.Fprintf(&b, "- `%s` — first touched in iteration %d\n", slug, firstTouched[slug])
		}
		b.WriteString("\n")
	}

	// Cost (fields only, never enforced).
	if eval != nil {
		b.WriteString("## Cost\n\n")
		fmt.Fprintf(&b, "| Field | Value |\n|---|---|\n| Dry-run estimate | %d val cases · ≈$%.2f per full-gate evaluation |\n| Budgets | recorded only, never enforced — user-assigned budgets are Phase F3 |\n\n",
			eval.Estimate.EstimatedValCases, eval.Estimate.EstimatedCostUSD)
	}

	// Limitations.
	b.WriteString("## Limitations\n\n")
	fmt.Fprintf(&b, "- Patterns added: %d. The v0 evolution flow is additive — it never prunes, deduplicates, or rewrites existing wiki sections (layer pruning is a later plan item).\n", len(order))
	fmt.Fprintf(&b, "- Scorer %s: the gate compares candidate structure, not model answers — scores are deterministic heuristics; versioned scorer and eval store are later stories.\n", SkillAuditScorerVersion)
	b.WriteString("- Cost budgets are recorded but not enforced (Phase F3 owns enforcement).\n")
	if n := countDecidedAgainst(iterations); n > 0 {
		fmt.Fprintf(&b, "- %d iteration(s) ended rejected or interrupted and left the live skill byte-identical (auto-revert).\n", n)
	}
	b.WriteString("\n")

	// Trained state at publication.
	b.WriteString("## Trained state at publication\n\n")
	fmt.Fprintf(&b, "%s.\n\n", trainedStateAtPublication(trained))
	b.WriteString("Staleness is derived live, never stored here: if the eval set is re-uploaded after this run, the skill is edited after training, or the marker is revoked, the wizard's Review step and `GET /api/skills/" + job.SkillSlug + "/trained-state` report `stale` with the reason.\n\n")

	// Reproduction notes.
	b.WriteString("## Reproduction\n\n")
	fmt.Fprintf(&b, "- Gate decisions for this skill: appended to `data/skill_audit.jsonl` (records for `%s`).\n", job.SkillSlug)
	fmt.Fprintf(&b, "- Run records: `data/skill_jobs/%s.json` plus `data/skill_jobs/%s.files/` (loop state, per-iteration records, eval splits + meta).\n", job.ID, job.ID)
	b.WriteString("- To re-run: create a new evolution job over MCP (`create_evolution_job`), upload the same eval file (the hash above must match), and dispatch from the same profile — the gate math, records, and a fresh report regenerate from the new run.\n")
	if eval != nil {
		fmt.Fprintf(&b, "- Eval source of record: %s (the hash above is over the stored, split-tagged cases).\n", eval.Filename)
	}
	b.WriteString("\n")

	// Amendments footer: the immutability convention, stated where a human reads.
	b.WriteString("## Amendments\n\n")
	b.WriteString("_This report was generated once, when the run ended, and agents cannot edit it (the `wikiskill-report` marker refuses agent writes). Humans may amend it by appending a dated, signed note below this line — leave the generated sections untouched._\n")
	return b.String()
}
